### ISSUE TITLE
next, current, prev

### ISSUE THREAD

**Issue by gitFrank** [debascoguy/FlexiblePaginationJS#1]
Hi, your plugin worked immediately. Thanks for that.
Test it with 100 items, 5 per page. If i set displayedPages: 3 i see this:
<<  <  1  ...  18  19  >  >>
Expected was 1 2 3. Maybe i'm understand wrong?

Also would be nice if all strings can translated easier, not in the JS file.
E.g.  Showing 1 to 5 of 100 Entries

**Comment by debascoguy** [comment]
<< < 1 ... 18 19 > >>
   << means 'First Page'
    < means 'Previous'
    >> means 'Last Page'
    > means 'Next'

   Since the total item is 100 and you set displayedPages: 3, The ... button is to remind Users that there are more pages that are not visible (i.e. due to your preference of limited displayPages of 3).
So, it shows that the last 2 pages are 18, and 19.

NOTE:
you can change the button icons to text with this settings options:
btnFirstText:  "First"
btnLastText: "Last"
btnPreviousText: "Previous"
btnNextText : "Next"


CLARIFICATION NEEDED HERE ON:
"Also would be nice if all strings can translated easier, not in the JS file.
E.g. Showing 1 to 5 of 100 Entries"


Thanks.

**Comment by JOHN748** [comment]
Hey...Thanks fr this plugin. I have one question how can i change search filter (keyup)  method to onclick button search method.

For example i've entering some text values in input field then it will filter the contents... I want that to filter when i click the button called search.  How can i do that. Pls help.
